vich_uploader:
  db_driver: orm

  mappings:
    photos:
      uri_prefix: /img/imgAnnonces
      upload_destination: "%kernel.project_dir%/public_html/img/imgAnnonces"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true
