#index:
#    path: /
#    controller: App\Controller\DefaultController::index

categories:
   path: /category
   controller: App\Controller\CategorieController::list

delete_category:
   path: /category/delete/{id}
   controller: App\Controller\CategorieController::delete

edit_category:
   path: /category/edit/{id}
   controller: App\Controller\CategorieController::edit

annonce_info:
   path: /annonce/{id}
   controller: App\Controller\AnnonceController::show
