<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLLuygxR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLLuygxR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLLuygxR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLLuygxR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLLuygxR\App_KernelDevDebugContainer([
    'container.build_hash' => 'LLuygxR',
    'container.build_id' => '829d4f9a',
    'container.build_time' => 1639049151,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLLuygxR');
